# Generated by Django 5.0.6 on 2024-05-26 21:49

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_rentbicycle_reserveddates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.product')),
                ('name', models.CharField(max_length=30)),
            ],
            bases=('api.product',),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oib', models.CharField(max_length=9)),
                ('date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='SaleBicycle',
            fields=[
                ('bicycle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.bicycle')),
                ('price', models.FloatField()),
                ('availability', models.IntegerField()),
            ],
            bases=('api.bicycle',),
        ),
        migrations.CreateModel(
            name='RentEquipment',
            fields=[
                ('equipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.equipment')),
                ('reservedDates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), default=list, size=None)),
                ('pricePerDay', models.FloatField()),
            ],
            bases=('api.equipment',),
        ),
        migrations.CreateModel(
            name='SaleEquipment',
            fields=[
                ('equipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.equipment')),
                ('price', models.FloatField()),
                ('availability', models.IntegerField()),
            ],
            bases=('api.equipment',),
        ),
        migrations.CreateModel(
            name='ReservationRent',
            fields=[
                ('reservation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.reservation')),
                ('reservedDates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), default=list, size=None)),
            ],
            bases=('api.reservation',),
        ),
        migrations.CreateModel(
            name='ReservationSale',
            fields=[
                ('reservation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.reservation')),
                ('dateToCollect', models.DateField()),
            ],
            bases=('api.reservation',),
        ),
    ]
