# Generated by Django 5.0.6 on 2024-05-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_equipment_reservation_salebicycle_rentequipment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='product',
        ),
        migrations.AddField(
            model_name='reservation',
            name='products',
            field=models.ManyToManyField(to='api.product'),
        ),
    ]
